kind: Service
apiVersion: v1
metadata:
  name: actifact-svc
  labels:
    app: actifact
spec:
  type: NodePort
  selector:
    app: actifact
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: actifact-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actifact
  template:
    metadata:
      labels:
        app: actifact
        version: v1
    spec:
      containers:
      - name: actifact-server
        image: actifact-server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
